# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Build Vue
        run: |
          yarn install --frozen-lockfile
          yarn build
          cd dist
          echo 'www.challen.info' > CNAME
          git config --global user.email $GITHUB_ACTOR
          git config --global user.name CI

          git init
          git add -A
          git commit -m deploy
          git push -f https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git master:gh-pages
        shell: bash
# - name: Vue to Github Pages
#   uses: xRealNeon/VuePagesAction@1.0.0
#   with:
#     username: areve
#     reponame: website
#     token: ${{ secrets.GITHUB_TOKEN }}
#     cname: www.challen.info
