name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Vue
        run: |
          yarn install --frozen-lockfile
          yarn build
          cd dist
          echo 'www.challen.info' > CNAME
          echo GITHUB_ACTOR $GITHUB_ACTOR
          echo GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}
          echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
          git config --global user.email $GITHUB_ACTOR
          git config --global user.name CI

          git init
          git add -A
          git commit -m deploy
          git push -f https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git master:gh-pages
        shell: bash
# - name: Vue to Github Pages
#   uses: xRealNeon/VuePagesAction@1.0.0
#   with:
#     username: areve
#     reponame: website
#     token: ${{ secrets.GITHUB_TOKEN }}
#     cname: www.challen.info
